networks:
    dummies-network:
        external: true

services:
    emisor-gui:
        image: dummies-gui:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: emisor-gui
        hostname: emisor-gui
        depends_on:
            -   mqtt-broker
        networks:
            - dummies-network
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /dev/bus/usb:/dev/bus/usb:ro
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - $HOME/.Xauthority:/root/.Xauthority:ro
            - .:/app
        device_cgroup_rules:
            - c 189:* rmw
        working_dir: /app
        command: python3 emisor.py

    receptor-gui:
        image: dummies-gui:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: receptor-gui
        hostname: receptor-gui
        depends_on:
            -   mqtt-broker
        networks:
            - dummies-network
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /dev/bus/usb:/dev/bus/usb:ro
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - $HOME/.Xauthority:/root/.Xauthority:ro
            - .:/app
        device_cgroup_rules:
            - c 189:* rmw
        working_dir: /app
        command: python3 receptor.py

    mqtt-broker:
        image: eclipse-mosquitto:2.0-openssl
        container_name: mqtt-broker
        hostname: mqtt-broker
        networks:
            - dummies-network
        ports:
            - "1883:1883"
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:z
        tty: true
        command: mosquitto -c /mosquitto/config/mosquitto.conf
