networks:
    dummies-network:
        external: true

services:
    transmitter-gui:
        image: dummies-gui:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: transmitter-gui
        hostname: transmitter-gui
        networks:
            - dummies-network
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /dev/bus/usb:/dev/bus/usb:ro
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - $HOME/.Xauthority:/root/.Xauthority:ro
            - .:/app
        device_cgroup_rules:
            - c 189:* rmw
        working_dir: /app/transmitter
        command: python3 transmitter-gui.py

    receiver-gui:
        image: dummies-gui:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: receiver-gui
        hostname: receiver-gui
        networks:
            - dummies-network
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /dev/bus/usb:/dev/bus/usb:ro
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - $HOME/.Xauthority:/root/.Xauthority:ro
            - .:/app
        device_cgroup_rules:
            - c 189:* rmw
        working_dir: /app/receiver
        command: python3 -u receiver-gui.py
