"""The keys used for the events or layout elements in the GUI"""

import enum

class Keys(enum.Enum):
  EXIT_1 = "-EXIT-1-"
  EXIT_2 = "-EXIT-2-"
  EXIT_3 = "-EXIT-3-"
  MESSAGE = "-MESSAGE-"
  RECEIVE = "-RECEIVE-"
  STOP = "-STOP-"
  CLEAN = "-CLEAN-"
  DIR_NAME = "-DIR_NAME-"
  FILE_NAME = "-FILE_NAME-"
  PATH_ERROR_MSG = "-PATH-ERROR-MSG-"
  SAVE = "-SAVE-"
  EXPERIMENT_ID = "-EXPERIMENT_ID-"
  EXPERIMENT_TABLE = "-EXPERIMENT_TABLE-"
  GET_EXPERIMENT = "-GET_EXPERIMENT-"
  EXP_SAVE_DIR = "-EXP_SAVE_DIR-"
  # Param keys
  DISTANCE_PARAM = "-DISTANCE_PARAM-"
  ANGLE_PARAM = "-ANGLE_PARAM-"
  INTENSITY_PARAM = "-INTENSITY_PARAM-"
  FREQUENCY_PARAM = "-FREQUENCY_PARAM-"
  BATCH_PARAM = "-BATCH_PARAM-"
  # Visibility related keys
  TOGGLE_SEC_SAVE_FILE = "-TOGGLE_SEC-SAVE_FILE-"
  TOGGLE_SEC_SHOW_TEXT = "-TOGGLE_SEC-SHOW_TEXT-"
  TOGGLE_SEC_EXPERIMENT = "-TOGGLE_SEC-EXPERIMENT-"
  # Section related keys
  SEC_SHOW_TEXT = "-SEC-SHOW_TEXT-"
  SEC_SAVE_FILE =  "-SEC-SAVE_FILE-"
  SEC_EXPERIMENT = "-SEC-EXPERIMENT-"

VISIBILITY_KEYS = [
  Keys.TOGGLE_SEC_SAVE_FILE,
  Keys.TOGGLE_SEC_SHOW_TEXT,
  Keys.TOGGLE_SEC_EXPERIMENT,
]

EXIT_KEYS = [
  Keys.EXIT_1,
  Keys.EXIT_2,
  Keys.EXIT_3
]