"""The keys used for the events or layout elements in the GUI"""

import enum

class Keys(enum.Enum):
  EXIT = "-EXIT-"
  MESSAGE = "-MESSAGE-"
  RECEIVE = "-RECEIVE-"
  STOP = "-STOP-"
  CLEAN = "-CLEAN-"
  DIR_NAME = "-DIR_NAME-"
  FILE_NAME = "-FILE_NAME-"
  FILES_PATH = "-FILES_PATH-"
  PATH_ERROR_MSG = "-PATH_ERROR_MSG-"
  REMOVE_SELECTED_FILES = "-REMOVE_SELECTED_FILES-"
  SAVE = "-SAVE-"
  SAVE_ALL = "-SAVE_ALL-"
  RECEIVE_SEQUENCE = "-RECEIVE_SEQUENCE-"
  # Visibility related keys
  TOGGLE_SEC_SAVE_FILE = "-TOGGLE_SEC_SAVE_FILE-"
  TOGGLE_SEC_SHOW_TEXT = "-TOGGLE_SEC-SHOW_TEXT-"
  TOGGLE_SEC_SEQUENCE = "-TOGGLE_SEC_SEQUENCE-"
  # Section related keys
  SEC_SHOW_TEXT = "-SEC_SHOW_TEXT-"
  SEC_SAVE_FILE =  "-SEC_SAVE_FILE-"
  SEC_SEQUENCE =  "-SEC_SEQUENCE-"


VISIBILITY_KEYS = [
  Keys.TOGGLE_SEC_SAVE_FILE,
  Keys.TOGGLE_SEC_SHOW_TEXT,
  Keys.TOGGLE_SEC_SEQUENCE
]