"""The keys used for the events or layout elements in the GUI"""

import enum

class Keys(enum.Enum):
  EXIT = "-EXIT-"
  STOP = "-STOP-"
  SEND = "-SEND-"
  EXP_ID = "-EXP-ID-"
  LOAD_SETTINGS = "-LOAD_SETTINGS-"
  SAVE_SETTINGS = "-SAVE_SETTINGS-"
  DIR_PATH = "-DIR_PATH-"
  FILES_LIST = "-FILES_LIST-"
  FILES_PATH = "-FILES_PATH-"
  MESSAGE = "-MESSAGE-"
  # Visibility related keys
  TOGGLE_PLAIN_TEXT = "-TOGGLE_SEC-PLAIN_TEXT-"
  TOGGLE_FILE = "-TOGGLE_SEC-FILE-"
  TOGGLE_EXP = "-TOGGLE_SEC-EXP-"
  TOGGLE_SEQ = "-TOGGLE_SEC-SEQ-"
  # Section related keys
  SEC_FILE = "-SEC-FILE-"
  SEC_PLAIN_TEXT = "-SEC-PLAIN_TEXT-"
  SEC_EXP = "-SEC-EXP-"
  SEC_SEQ = "-SEC-SEQ-"
  STANDARD_SETTINGS = "-STANDARD_SETTINGS-"
  # Parameter keys
  PARAM_DUMMY_DISTANCE = "-PARAM-DUMMY_DISTANCE-"
  PARAM_TRANSMITTER_ANGLE = "-PARAM-TRANSMITTER_ANGLE-"
  PARAM_LED_INTENSITY = "-PARAM-LED_INTENSITY-"
  PARAM_BLINKING_FREQUENCY = "-PARAM-BLINKING_FREQUENCY-"
  PARAM_MESSAGES_BATCH = "-PARAM-MESSAGES_BATCH-"
  NEW_FILES = "-NEW_FILES-"
  REMOVE_SELECTED_FILES = "-REMOVE_SELECTED_FILES-"
  MOVE_UP = "-MOVE_UP-"
  MOVE_DOWN = "-MOVE_DOWN-"

PARAMETER_KEYS = [
  Keys.PARAM_DUMMY_DISTANCE,
  Keys.PARAM_TRANSMITTER_ANGLE,
  Keys.PARAM_LED_INTENSITY,
  Keys.PARAM_BLINKING_FREQUENCY,
  Keys.PARAM_MESSAGES_BATCH
]