import enum

class Keys(enum.Enum):
  EXP_ID = "-EXP_ID-"
  EXP_PROGRESS_TEXT = "-EXP_PROGRESS_TEXT-"
  CURRENT_EXP_PROGRESS = "-CURRENT_EXP_PROGRESS-"
  SEQ_PROGRESS_TEXT = "-SEQ_PROGRESS_TEXT-"
  CURRENT_SEQUENCE_PROGRESS = "-CURRENT_SEQUENCE_PROGRESS-"
  SKIP = "-SKIP-"
  STOP = "-STOP-"